// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.35.1
// 	protoc        (unknown)
// source: io/unmango/v1alpha1/ast.proto

package unmangov1alpha1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type String struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Value string `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *String) Reset() {
	*x = String{}
	mi := &file_io_unmango_v1alpha1_ast_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *String) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*String) ProtoMessage() {}

func (x *String) ProtoReflect() protoreflect.Message {
	mi := &file_io_unmango_v1alpha1_ast_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use String.ProtoReflect.Descriptor instead.
func (*String) Descriptor() ([]byte, []int) {
	return file_io_unmango_v1alpha1_ast_proto_rawDescGZIP(), []int{0}
}

func (x *String) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type Node struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Value:
	//
	//	*Node_Str
	//	*Node_File
	Value isNode_Value `protobuf_oneof:"value"`
}

func (x *Node) Reset() {
	*x = Node{}
	mi := &file_io_unmango_v1alpha1_ast_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Node) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Node) ProtoMessage() {}

func (x *Node) ProtoReflect() protoreflect.Message {
	mi := &file_io_unmango_v1alpha1_ast_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Node.ProtoReflect.Descriptor instead.
func (*Node) Descriptor() ([]byte, []int) {
	return file_io_unmango_v1alpha1_ast_proto_rawDescGZIP(), []int{1}
}

func (m *Node) GetValue() isNode_Value {
	if m != nil {
		return m.Value
	}
	return nil
}

func (x *Node) GetStr() *String {
	if x, ok := x.GetValue().(*Node_Str); ok {
		return x.Str
	}
	return nil
}

func (x *Node) GetFile() *File {
	if x, ok := x.GetValue().(*Node_File); ok {
		return x.File
	}
	return nil
}

type isNode_Value interface {
	isNode_Value()
}

type Node_Str struct {
	Str *String `protobuf:"bytes,1,opt,name=str,proto3,oneof"`
}

type Node_File struct {
	File *File `protobuf:"bytes,2,opt,name=file,proto3,oneof"`
}

func (*Node_Str) isNode_Value() {}

func (*Node_File) isNode_Value() {}

type Decl struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Decl) Reset() {
	*x = Decl{}
	mi := &file_io_unmango_v1alpha1_ast_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Decl) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Decl) ProtoMessage() {}

func (x *Decl) ProtoReflect() protoreflect.Message {
	mi := &file_io_unmango_v1alpha1_ast_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Decl.ProtoReflect.Descriptor instead.
func (*Decl) Descriptor() ([]byte, []int) {
	return file_io_unmango_v1alpha1_ast_proto_rawDescGZIP(), []int{2}
}

type File struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Decls []*Decl `protobuf:"bytes,1,rep,name=decls,proto3" json:"decls,omitempty"`
}

func (x *File) Reset() {
	*x = File{}
	mi := &file_io_unmango_v1alpha1_ast_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *File) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*File) ProtoMessage() {}

func (x *File) ProtoReflect() protoreflect.Message {
	mi := &file_io_unmango_v1alpha1_ast_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use File.ProtoReflect.Descriptor instead.
func (*File) Descriptor() ([]byte, []int) {
	return file_io_unmango_v1alpha1_ast_proto_rawDescGZIP(), []int{3}
}

func (x *File) GetDecls() []*Decl {
	if x != nil {
		return x.Decls
	}
	return nil
}

type VisitRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Node *Node `protobuf:"bytes,2,opt,name=node,proto3" json:"node,omitempty"`
}

func (x *VisitRequest) Reset() {
	*x = VisitRequest{}
	mi := &file_io_unmango_v1alpha1_ast_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VisitRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VisitRequest) ProtoMessage() {}

func (x *VisitRequest) ProtoReflect() protoreflect.Message {
	mi := &file_io_unmango_v1alpha1_ast_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VisitRequest.ProtoReflect.Descriptor instead.
func (*VisitRequest) Descriptor() ([]byte, []int) {
	return file_io_unmango_v1alpha1_ast_proto_rawDescGZIP(), []int{4}
}

func (x *VisitRequest) GetNode() *Node {
	if x != nil {
		return x.Node
	}
	return nil
}

type VisitResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Continue bool `protobuf:"varint,1,opt,name=continue,proto3" json:"continue,omitempty"`
}

func (x *VisitResponse) Reset() {
	*x = VisitResponse{}
	mi := &file_io_unmango_v1alpha1_ast_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VisitResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VisitResponse) ProtoMessage() {}

func (x *VisitResponse) ProtoReflect() protoreflect.Message {
	mi := &file_io_unmango_v1alpha1_ast_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VisitResponse.ProtoReflect.Descriptor instead.
func (*VisitResponse) Descriptor() ([]byte, []int) {
	return file_io_unmango_v1alpha1_ast_proto_rawDescGZIP(), []int{5}
}

func (x *VisitResponse) GetContinue() bool {
	if x != nil {
		return x.Continue
	}
	return false
}

type WalkRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Uri  string `protobuf:"bytes,1,opt,name=uri,proto3" json:"uri,omitempty"`
	Node *Node  `protobuf:"bytes,2,opt,name=node,proto3" json:"node,omitempty"`
}

func (x *WalkRequest) Reset() {
	*x = WalkRequest{}
	mi := &file_io_unmango_v1alpha1_ast_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WalkRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WalkRequest) ProtoMessage() {}

func (x *WalkRequest) ProtoReflect() protoreflect.Message {
	mi := &file_io_unmango_v1alpha1_ast_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WalkRequest.ProtoReflect.Descriptor instead.
func (*WalkRequest) Descriptor() ([]byte, []int) {
	return file_io_unmango_v1alpha1_ast_proto_rawDescGZIP(), []int{6}
}

func (x *WalkRequest) GetUri() string {
	if x != nil {
		return x.Uri
	}
	return ""
}

func (x *WalkRequest) GetNode() *Node {
	if x != nil {
		return x.Node
	}
	return nil
}

type WalkResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *WalkResponse) Reset() {
	*x = WalkResponse{}
	mi := &file_io_unmango_v1alpha1_ast_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WalkResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WalkResponse) ProtoMessage() {}

func (x *WalkResponse) ProtoReflect() protoreflect.Message {
	mi := &file_io_unmango_v1alpha1_ast_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WalkResponse.ProtoReflect.Descriptor instead.
func (*WalkResponse) Descriptor() ([]byte, []int) {
	return file_io_unmango_v1alpha1_ast_proto_rawDescGZIP(), []int{7}
}

var File_io_unmango_v1alpha1_ast_proto protoreflect.FileDescriptor

var file_io_unmango_v1alpha1_ast_proto_rawDesc = []byte{
	0x0a, 0x1d, 0x69, 0x6f, 0x2f, 0x75, 0x6e, 0x6d, 0x61, 0x6e, 0x67, 0x6f, 0x2f, 0x76, 0x31, 0x61,
	0x6c, 0x70, 0x68, 0x61, 0x31, 0x2f, 0x61, 0x73, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x13, 0x69, 0x6f, 0x2e, 0x75, 0x6e, 0x6d, 0x61, 0x6e, 0x67, 0x6f, 0x2e, 0x76, 0x31, 0x61, 0x6c,
	0x70, 0x68, 0x61, 0x31, 0x22, 0x1e, 0x0a, 0x06, 0x53, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x12, 0x14,
	0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x76,
	0x61, 0x6c, 0x75, 0x65, 0x22, 0x71, 0x0a, 0x04, 0x4e, 0x6f, 0x64, 0x65, 0x12, 0x2f, 0x0a, 0x03,
	0x73, 0x74, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1b, 0x2e, 0x69, 0x6f, 0x2e, 0x75,
	0x6e, 0x6d, 0x61, 0x6e, 0x67, 0x6f, 0x2e, 0x76, 0x31, 0x61, 0x6c, 0x70, 0x68, 0x61, 0x31, 0x2e,
	0x53, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x48, 0x00, 0x52, 0x03, 0x73, 0x74, 0x72, 0x12, 0x2f, 0x0a,
	0x04, 0x66, 0x69, 0x6c, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x19, 0x2e, 0x69, 0x6f,
	0x2e, 0x75, 0x6e, 0x6d, 0x61, 0x6e, 0x67, 0x6f, 0x2e, 0x76, 0x31, 0x61, 0x6c, 0x70, 0x68, 0x61,
	0x31, 0x2e, 0x46, 0x69, 0x6c, 0x65, 0x48, 0x00, 0x52, 0x04, 0x66, 0x69, 0x6c, 0x65, 0x42, 0x07,
	0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x22, 0x06, 0x0a, 0x04, 0x44, 0x65, 0x63, 0x6c, 0x22,
	0x37, 0x0a, 0x04, 0x46, 0x69, 0x6c, 0x65, 0x12, 0x2f, 0x0a, 0x05, 0x64, 0x65, 0x63, 0x6c, 0x73,
	0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x19, 0x2e, 0x69, 0x6f, 0x2e, 0x75, 0x6e, 0x6d, 0x61,
	0x6e, 0x67, 0x6f, 0x2e, 0x76, 0x31, 0x61, 0x6c, 0x70, 0x68, 0x61, 0x31, 0x2e, 0x44, 0x65, 0x63,
	0x6c, 0x52, 0x05, 0x64, 0x65, 0x63, 0x6c, 0x73, 0x22, 0x3d, 0x0a, 0x0c, 0x56, 0x69, 0x73, 0x69,
	0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x2d, 0x0a, 0x04, 0x6e, 0x6f, 0x64, 0x65,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x19, 0x2e, 0x69, 0x6f, 0x2e, 0x75, 0x6e, 0x6d, 0x61,
	0x6e, 0x67, 0x6f, 0x2e, 0x76, 0x31, 0x61, 0x6c, 0x70, 0x68, 0x61, 0x31, 0x2e, 0x4e, 0x6f, 0x64,
	0x65, 0x52, 0x04, 0x6e, 0x6f, 0x64, 0x65, 0x22, 0x2b, 0x0a, 0x0d, 0x56, 0x69, 0x73, 0x69, 0x74,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x63, 0x6f, 0x6e, 0x74,
	0x69, 0x6e, 0x75, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x08, 0x63, 0x6f, 0x6e, 0x74,
	0x69, 0x6e, 0x75, 0x65, 0x22, 0x4e, 0x0a, 0x0b, 0x57, 0x61, 0x6c, 0x6b, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x72, 0x69, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x03, 0x75, 0x72, 0x69, 0x12, 0x2d, 0x0a, 0x04, 0x6e, 0x6f, 0x64, 0x65, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x19, 0x2e, 0x69, 0x6f, 0x2e, 0x75, 0x6e, 0x6d, 0x61, 0x6e, 0x67, 0x6f,
	0x2e, 0x76, 0x31, 0x61, 0x6c, 0x70, 0x68, 0x61, 0x31, 0x2e, 0x4e, 0x6f, 0x64, 0x65, 0x52, 0x04,
	0x6e, 0x6f, 0x64, 0x65, 0x22, 0x0e, 0x0a, 0x0c, 0x57, 0x61, 0x6c, 0x6b, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x32, 0x60, 0x0a, 0x0e, 0x56, 0x69, 0x73, 0x69, 0x74, 0x6f, 0x72, 0x53,
	0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x4e, 0x0a, 0x05, 0x56, 0x69, 0x73, 0x69, 0x74, 0x12,
	0x21, 0x2e, 0x69, 0x6f, 0x2e, 0x75, 0x6e, 0x6d, 0x61, 0x6e, 0x67, 0x6f, 0x2e, 0x76, 0x31, 0x61,
	0x6c, 0x70, 0x68, 0x61, 0x31, 0x2e, 0x56, 0x69, 0x73, 0x69, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x22, 0x2e, 0x69, 0x6f, 0x2e, 0x75, 0x6e, 0x6d, 0x61, 0x6e, 0x67, 0x6f, 0x2e,
	0x76, 0x31, 0x61, 0x6c, 0x70, 0x68, 0x61, 0x31, 0x2e, 0x56, 0x69, 0x73, 0x69, 0x74, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x32, 0x59, 0x0a, 0x0a, 0x41, 0x73, 0x74, 0x53, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x12, 0x4b, 0x0a, 0x04, 0x57, 0x61, 0x6c, 0x6b, 0x12, 0x20, 0x2e, 0x69,
	0x6f, 0x2e, 0x75, 0x6e, 0x6d, 0x61, 0x6e, 0x67, 0x6f, 0x2e, 0x76, 0x31, 0x61, 0x6c, 0x70, 0x68,
	0x61, 0x31, 0x2e, 0x57, 0x61, 0x6c, 0x6b, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x21,
	0x2e, 0x69, 0x6f, 0x2e, 0x75, 0x6e, 0x6d, 0x61, 0x6e, 0x67, 0x6f, 0x2e, 0x76, 0x31, 0x61, 0x6c,
	0x70, 0x68, 0x61, 0x31, 0x2e, 0x57, 0x61, 0x6c, 0x6b, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x42, 0xdb, 0x01, 0x0a, 0x17, 0x63, 0x6f, 0x6d, 0x2e, 0x69, 0x6f, 0x2e, 0x75, 0x6e, 0x6d,
	0x61, 0x6e, 0x67, 0x6f, 0x2e, 0x76, 0x31, 0x61, 0x6c, 0x70, 0x68, 0x61, 0x31, 0x42, 0x08, 0x41,
	0x73, 0x74, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x50, 0x01, 0x5a, 0x48, 0x67, 0x69, 0x74, 0x68, 0x75,
	0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x75, 0x6e, 0x73, 0x74, 0x6f, 0x70, 0x70, 0x61, 0x62, 0x6c,
	0x65, 0x6d, 0x61, 0x6e, 0x67, 0x6f, 0x2f, 0x6c, 0x61, 0x6e, 0x67, 0x2f, 0x70, 0x6b, 0x67, 0x2f,
	0x69, 0x6f, 0x2f, 0x75, 0x6e, 0x6d, 0x61, 0x6e, 0x67, 0x6f, 0x2f, 0x76, 0x31, 0x61, 0x6c, 0x70,
	0x68, 0x61, 0x31, 0x3b, 0x75, 0x6e, 0x6d, 0x61, 0x6e, 0x67, 0x6f, 0x76, 0x31, 0x61, 0x6c, 0x70,
	0x68, 0x61, 0x31, 0xa2, 0x02, 0x03, 0x49, 0x55, 0x58, 0xaa, 0x02, 0x13, 0x49, 0x6f, 0x2e, 0x55,
	0x6e, 0x6d, 0x61, 0x6e, 0x67, 0x6f, 0x2e, 0x56, 0x31, 0x61, 0x6c, 0x70, 0x68, 0x61, 0x31, 0xca,
	0x02, 0x13, 0x49, 0x6f, 0x5c, 0x55, 0x6e, 0x6d, 0x61, 0x6e, 0x67, 0x6f, 0x5c, 0x56, 0x31, 0x61,
	0x6c, 0x70, 0x68, 0x61, 0x31, 0xe2, 0x02, 0x1f, 0x49, 0x6f, 0x5c, 0x55, 0x6e, 0x6d, 0x61, 0x6e,
	0x67, 0x6f, 0x5c, 0x56, 0x31, 0x61, 0x6c, 0x70, 0x68, 0x61, 0x31, 0x5c, 0x47, 0x50, 0x42, 0x4d,
	0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0xea, 0x02, 0x15, 0x49, 0x6f, 0x3a, 0x3a, 0x55, 0x6e,
	0x6d, 0x61, 0x6e, 0x67, 0x6f, 0x3a, 0x3a, 0x56, 0x31, 0x61, 0x6c, 0x70, 0x68, 0x61, 0x31, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_io_unmango_v1alpha1_ast_proto_rawDescOnce sync.Once
	file_io_unmango_v1alpha1_ast_proto_rawDescData = file_io_unmango_v1alpha1_ast_proto_rawDesc
)

func file_io_unmango_v1alpha1_ast_proto_rawDescGZIP() []byte {
	file_io_unmango_v1alpha1_ast_proto_rawDescOnce.Do(func() {
		file_io_unmango_v1alpha1_ast_proto_rawDescData = protoimpl.X.CompressGZIP(file_io_unmango_v1alpha1_ast_proto_rawDescData)
	})
	return file_io_unmango_v1alpha1_ast_proto_rawDescData
}

var file_io_unmango_v1alpha1_ast_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_io_unmango_v1alpha1_ast_proto_goTypes = []any{
	(*String)(nil),        // 0: io.unmango.v1alpha1.String
	(*Node)(nil),          // 1: io.unmango.v1alpha1.Node
	(*Decl)(nil),          // 2: io.unmango.v1alpha1.Decl
	(*File)(nil),          // 3: io.unmango.v1alpha1.File
	(*VisitRequest)(nil),  // 4: io.unmango.v1alpha1.VisitRequest
	(*VisitResponse)(nil), // 5: io.unmango.v1alpha1.VisitResponse
	(*WalkRequest)(nil),   // 6: io.unmango.v1alpha1.WalkRequest
	(*WalkResponse)(nil),  // 7: io.unmango.v1alpha1.WalkResponse
}
var file_io_unmango_v1alpha1_ast_proto_depIdxs = []int32{
	0, // 0: io.unmango.v1alpha1.Node.str:type_name -> io.unmango.v1alpha1.String
	3, // 1: io.unmango.v1alpha1.Node.file:type_name -> io.unmango.v1alpha1.File
	2, // 2: io.unmango.v1alpha1.File.decls:type_name -> io.unmango.v1alpha1.Decl
	1, // 3: io.unmango.v1alpha1.VisitRequest.node:type_name -> io.unmango.v1alpha1.Node
	1, // 4: io.unmango.v1alpha1.WalkRequest.node:type_name -> io.unmango.v1alpha1.Node
	4, // 5: io.unmango.v1alpha1.VisitorService.Visit:input_type -> io.unmango.v1alpha1.VisitRequest
	6, // 6: io.unmango.v1alpha1.AstService.Walk:input_type -> io.unmango.v1alpha1.WalkRequest
	5, // 7: io.unmango.v1alpha1.VisitorService.Visit:output_type -> io.unmango.v1alpha1.VisitResponse
	7, // 8: io.unmango.v1alpha1.AstService.Walk:output_type -> io.unmango.v1alpha1.WalkResponse
	7, // [7:9] is the sub-list for method output_type
	5, // [5:7] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_io_unmango_v1alpha1_ast_proto_init() }
func file_io_unmango_v1alpha1_ast_proto_init() {
	if File_io_unmango_v1alpha1_ast_proto != nil {
		return
	}
	file_io_unmango_v1alpha1_ast_proto_msgTypes[1].OneofWrappers = []any{
		(*Node_Str)(nil),
		(*Node_File)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_io_unmango_v1alpha1_ast_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_io_unmango_v1alpha1_ast_proto_goTypes,
		DependencyIndexes: file_io_unmango_v1alpha1_ast_proto_depIdxs,
		MessageInfos:      file_io_unmango_v1alpha1_ast_proto_msgTypes,
	}.Build()
	File_io_unmango_v1alpha1_ast_proto = out.File
	file_io_unmango_v1alpha1_ast_proto_rawDesc = nil
	file_io_unmango_v1alpha1_ast_proto_goTypes = nil
	file_io_unmango_v1alpha1_ast_proto_depIdxs = nil
}
