// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             (unknown)
// source: io/unmango/v1alpha1/ast.proto

package unmangov1alpha1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	VisitorService_Visit_FullMethodName = "/io.unmango.v1alpha1.VisitorService/Visit"
)

// VisitorServiceClient is the client API for VisitorService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type VisitorServiceClient interface {
	Visit(ctx context.Context, in *VisitRequest, opts ...grpc.CallOption) (*VisitResponse, error)
}

type visitorServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewVisitorServiceClient(cc grpc.ClientConnInterface) VisitorServiceClient {
	return &visitorServiceClient{cc}
}

func (c *visitorServiceClient) Visit(ctx context.Context, in *VisitRequest, opts ...grpc.CallOption) (*VisitResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(VisitResponse)
	err := c.cc.Invoke(ctx, VisitorService_Visit_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// VisitorServiceServer is the server API for VisitorService service.
// All implementations must embed UnimplementedVisitorServiceServer
// for forward compatibility.
type VisitorServiceServer interface {
	Visit(context.Context, *VisitRequest) (*VisitResponse, error)
	mustEmbedUnimplementedVisitorServiceServer()
}

// UnimplementedVisitorServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedVisitorServiceServer struct{}

func (UnimplementedVisitorServiceServer) Visit(context.Context, *VisitRequest) (*VisitResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Visit not implemented")
}
func (UnimplementedVisitorServiceServer) mustEmbedUnimplementedVisitorServiceServer() {}
func (UnimplementedVisitorServiceServer) testEmbeddedByValue()                        {}

// UnsafeVisitorServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to VisitorServiceServer will
// result in compilation errors.
type UnsafeVisitorServiceServer interface {
	mustEmbedUnimplementedVisitorServiceServer()
}

func RegisterVisitorServiceServer(s grpc.ServiceRegistrar, srv VisitorServiceServer) {
	// If the following call pancis, it indicates UnimplementedVisitorServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&VisitorService_ServiceDesc, srv)
}

func _VisitorService_Visit_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VisitRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VisitorServiceServer).Visit(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VisitorService_Visit_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VisitorServiceServer).Visit(ctx, req.(*VisitRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// VisitorService_ServiceDesc is the grpc.ServiceDesc for VisitorService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var VisitorService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "io.unmango.v1alpha1.VisitorService",
	HandlerType: (*VisitorServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Visit",
			Handler:    _VisitorService_Visit_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "io/unmango/v1alpha1/ast.proto",
}
