// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: io/unmango/v1alpha1/ast.proto

#include "io/unmango/v1alpha1/ast.pb.h"
#include "io/unmango/v1alpha1/ast.grpc.pb.h"

#include <functional>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/impl/channel_interface.h>
#include <grpcpp/impl/client_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/rpc_service_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/sync_stream.h>
namespace io {
namespace unmango {
namespace v1alpha1 {

}  // namespace io
}  // namespace unmango
}  // namespace v1alpha1

