// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: io/unmango/v1alpha1/parser.proto
#ifndef GRPC_io_2funmango_2fv1alpha1_2fparser_2eproto__INCLUDED
#define GRPC_io_2funmango_2fv1alpha1_2fparser_2eproto__INCLUDED

#include "io/unmango/v1alpha1/parser.pb.h"

#include <functional>
#include <grpcpp/generic/async_generic_service.h>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/client_context.h>
#include <grpcpp/completion_queue.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/proto_utils.h>
#include <grpcpp/impl/rpc_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/status.h>
#include <grpcpp/support/stub_options.h>
#include <grpcpp/support/sync_stream.h>

namespace io {
namespace unmango {
namespace v1alpha1 {

class ParserService final {
 public:
  static constexpr char const* service_full_name() {
    return "io.unmango.v1alpha1.ParserService";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    virtual ::grpc::Status Parse(::grpc::ClientContext* context, const ::io::unmango::v1alpha1::ParseRequest& request, ::io::unmango::v1alpha1::ParseResponse* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::io::unmango::v1alpha1::ParseResponse>> AsyncParse(::grpc::ClientContext* context, const ::io::unmango::v1alpha1::ParseRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::io::unmango::v1alpha1::ParseResponse>>(AsyncParseRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::io::unmango::v1alpha1::ParseResponse>> PrepareAsyncParse(::grpc::ClientContext* context, const ::io::unmango::v1alpha1::ParseRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::io::unmango::v1alpha1::ParseResponse>>(PrepareAsyncParseRaw(context, request, cq));
    }
    class async_interface {
     public:
      virtual ~async_interface() {}
      virtual void Parse(::grpc::ClientContext* context, const ::io::unmango::v1alpha1::ParseRequest* request, ::io::unmango::v1alpha1::ParseResponse* response, std::function<void(::grpc::Status)>) = 0;
      virtual void Parse(::grpc::ClientContext* context, const ::io::unmango::v1alpha1::ParseRequest* request, ::io::unmango::v1alpha1::ParseResponse* response, ::grpc::ClientUnaryReactor* reactor) = 0;
    };
    typedef class async_interface experimental_async_interface;
    virtual class async_interface* async() { return nullptr; }
    class async_interface* experimental_async() { return async(); }
   private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::io::unmango::v1alpha1::ParseResponse>* AsyncParseRaw(::grpc::ClientContext* context, const ::io::unmango::v1alpha1::ParseRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::io::unmango::v1alpha1::ParseResponse>* PrepareAsyncParseRaw(::grpc::ClientContext* context, const ::io::unmango::v1alpha1::ParseRequest& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());
    ::grpc::Status Parse(::grpc::ClientContext* context, const ::io::unmango::v1alpha1::ParseRequest& request, ::io::unmango::v1alpha1::ParseResponse* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::io::unmango::v1alpha1::ParseResponse>> AsyncParse(::grpc::ClientContext* context, const ::io::unmango::v1alpha1::ParseRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::io::unmango::v1alpha1::ParseResponse>>(AsyncParseRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::io::unmango::v1alpha1::ParseResponse>> PrepareAsyncParse(::grpc::ClientContext* context, const ::io::unmango::v1alpha1::ParseRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::io::unmango::v1alpha1::ParseResponse>>(PrepareAsyncParseRaw(context, request, cq));
    }
    class async final :
      public StubInterface::async_interface {
     public:
      void Parse(::grpc::ClientContext* context, const ::io::unmango::v1alpha1::ParseRequest* request, ::io::unmango::v1alpha1::ParseResponse* response, std::function<void(::grpc::Status)>) override;
      void Parse(::grpc::ClientContext* context, const ::io::unmango::v1alpha1::ParseRequest* request, ::io::unmango::v1alpha1::ParseResponse* response, ::grpc::ClientUnaryReactor* reactor) override;
     private:
      friend class Stub;
      explicit async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class async* async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class async async_stub_{this};
    ::grpc::ClientAsyncResponseReader< ::io::unmango::v1alpha1::ParseResponse>* AsyncParseRaw(::grpc::ClientContext* context, const ::io::unmango::v1alpha1::ParseRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::io::unmango::v1alpha1::ParseResponse>* PrepareAsyncParseRaw(::grpc::ClientContext* context, const ::io::unmango::v1alpha1::ParseRequest& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_Parse_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    virtual ::grpc::Status Parse(::grpc::ServerContext* context, const ::io::unmango::v1alpha1::ParseRequest* request, ::io::unmango::v1alpha1::ParseResponse* response);
  };
  template <class BaseClass>
  class WithAsyncMethod_Parse : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_Parse() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_Parse() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Parse(::grpc::ServerContext* /*context*/, const ::io::unmango::v1alpha1::ParseRequest* /*request*/, ::io::unmango::v1alpha1::ParseResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestParse(::grpc::ServerContext* context, ::io::unmango::v1alpha1::ParseRequest* request, ::grpc::ServerAsyncResponseWriter< ::io::unmango::v1alpha1::ParseResponse>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_Parse<Service > AsyncService;
  template <class BaseClass>
  class WithCallbackMethod_Parse : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_Parse() {
      ::grpc::Service::MarkMethodCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::io::unmango::v1alpha1::ParseRequest, ::io::unmango::v1alpha1::ParseResponse>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::io::unmango::v1alpha1::ParseRequest* request, ::io::unmango::v1alpha1::ParseResponse* response) { return this->Parse(context, request, response); }));}
    void SetMessageAllocatorFor_Parse(
        ::grpc::MessageAllocator< ::io::unmango::v1alpha1::ParseRequest, ::io::unmango::v1alpha1::ParseResponse>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(0);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::io::unmango::v1alpha1::ParseRequest, ::io::unmango::v1alpha1::ParseResponse>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_Parse() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Parse(::grpc::ServerContext* /*context*/, const ::io::unmango::v1alpha1::ParseRequest* /*request*/, ::io::unmango::v1alpha1::ParseResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* Parse(
      ::grpc::CallbackServerContext* /*context*/, const ::io::unmango::v1alpha1::ParseRequest* /*request*/, ::io::unmango::v1alpha1::ParseResponse* /*response*/)  { return nullptr; }
  };
  typedef WithCallbackMethod_Parse<Service > CallbackService;
  typedef CallbackService ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_Parse : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_Parse() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_Parse() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Parse(::grpc::ServerContext* /*context*/, const ::io::unmango::v1alpha1::ParseRequest* /*request*/, ::io::unmango::v1alpha1::ParseResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_Parse : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_Parse() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_Parse() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Parse(::grpc::ServerContext* /*context*/, const ::io::unmango::v1alpha1::ParseRequest* /*request*/, ::io::unmango::v1alpha1::ParseResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestParse(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_Parse : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_Parse() {
      ::grpc::Service::MarkMethodRawCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->Parse(context, request, response); }));
    }
    ~WithRawCallbackMethod_Parse() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Parse(::grpc::ServerContext* /*context*/, const ::io::unmango::v1alpha1::ParseRequest* /*request*/, ::io::unmango::v1alpha1::ParseResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* Parse(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_Parse : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_Parse() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::StreamedUnaryHandler<
          ::io::unmango::v1alpha1::ParseRequest, ::io::unmango::v1alpha1::ParseResponse>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::io::unmango::v1alpha1::ParseRequest, ::io::unmango::v1alpha1::ParseResponse>* streamer) {
                       return this->StreamedParse(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_Parse() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status Parse(::grpc::ServerContext* /*context*/, const ::io::unmango::v1alpha1::ParseRequest* /*request*/, ::io::unmango::v1alpha1::ParseResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedParse(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::io::unmango::v1alpha1::ParseRequest,::io::unmango::v1alpha1::ParseResponse>* server_unary_streamer) = 0;
  };
  typedef WithStreamedUnaryMethod_Parse<Service > StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef WithStreamedUnaryMethod_Parse<Service > StreamedService;
};

}  // namespace v1alpha1
}  // namespace unmango
}  // namespace io


#endif  // GRPC_io_2funmango_2fv1alpha1_2fparser_2eproto__INCLUDED
