// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: io/unmango/v1alpha1/parser.proto
// Protobuf C++ Version: 6.30.0

#include "io/unmango/v1alpha1/parser.pb.h"

#include <algorithm>
#include <type_traits>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/generated_message_tctable_impl.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;
namespace io {
namespace unmango {
namespace v1alpha1 {

inline constexpr ParseRequest::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        text_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()) {}

template <typename>
PROTOBUF_CONSTEXPR ParseRequest::ParseRequest(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(ParseRequest_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct ParseRequestDefaultTypeInternal {
  PROTOBUF_CONSTEXPR ParseRequestDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~ParseRequestDefaultTypeInternal() {}
  union {
    ParseRequest _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 ParseRequestDefaultTypeInternal _ParseRequest_default_instance_;

inline constexpr ParseResponse::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        file_{nullptr} {}

template <typename>
PROTOBUF_CONSTEXPR ParseResponse::ParseResponse(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(ParseResponse_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct ParseResponseDefaultTypeInternal {
  PROTOBUF_CONSTEXPR ParseResponseDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~ParseResponseDefaultTypeInternal() {}
  union {
    ParseResponse _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 ParseResponseDefaultTypeInternal _ParseResponse_default_instance_;
}  // namespace v1alpha1
}  // namespace unmango
}  // namespace io
static constexpr const ::_pb::EnumDescriptor *PROTOBUF_NONNULL *PROTOBUF_NULLABLE
    file_level_enum_descriptors_io_2funmango_2fv1alpha1_2fparser_2eproto = nullptr;
static constexpr const ::_pb::ServiceDescriptor *PROTOBUF_NONNULL *PROTOBUF_NULLABLE
    file_level_service_descriptors_io_2funmango_2fv1alpha1_2fparser_2eproto = nullptr;
const ::uint32_t
    TableStruct_io_2funmango_2fv1alpha1_2fparser_2eproto::offsets[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
        protodesc_cold) = {
        PROTOBUF_FIELD_OFFSET(::io::unmango::v1alpha1::ParseRequest, _impl_._has_bits_),
        PROTOBUF_FIELD_OFFSET(::io::unmango::v1alpha1::ParseRequest, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::io::unmango::v1alpha1::ParseRequest, _impl_.text_),
        0,
        PROTOBUF_FIELD_OFFSET(::io::unmango::v1alpha1::ParseResponse, _impl_._has_bits_),
        PROTOBUF_FIELD_OFFSET(::io::unmango::v1alpha1::ParseResponse, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::io::unmango::v1alpha1::ParseResponse, _impl_.file_),
        0,
};

static const ::_pbi::MigrationSchema
    schemas[] ABSL_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
        {0, 9, -1, sizeof(::io::unmango::v1alpha1::ParseRequest)},
        {10, 19, -1, sizeof(::io::unmango::v1alpha1::ParseResponse)},
};
static const ::_pb::Message* PROTOBUF_NONNULL const file_default_instances[] = {
    &::io::unmango::v1alpha1::_ParseRequest_default_instance_._instance,
    &::io::unmango::v1alpha1::_ParseResponse_default_instance_._instance,
};
const char descriptor_table_protodef_io_2funmango_2fv1alpha1_2fparser_2eproto[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
    protodesc_cold) = {
    "\n io/unmango/v1alpha1/parser.proto\022\023io.u"
    "nmango.v1alpha1\032\035io/unmango/v1alpha1/ast"
    ".proto\"\"\n\014ParseRequest\022\022\n\004text\030\001 \001(\tR\004te"
    "xt\">\n\rParseResponse\022-\n\004file\030\001 \001(\0132\031.io.u"
    "nmango.v1alpha1.FileR\004file2_\n\rParserServ"
    "ice\022N\n\005Parse\022!.io.unmango.v1alpha1.Parse"
    "Request\032\".io.unmango.v1alpha1.ParseRespo"
    "nseB\336\001\n\027com.io.unmango.v1alpha1B\013ParserP"
    "rotoP\001ZHgithub.com/unstoppablemango/lang"
    "/pkg/io/unmango/v1alpha1;unmangov1alpha1"
    "\242\002\003IUX\252\002\023Io.Unmango.V1alpha1\312\002\023Io\\Unmang"
    "o\\V1alpha1\342\002\037Io\\Unmango\\V1alpha1\\GPBMeta"
    "data\352\002\025Io::Unmango::V1alpha1b\006proto3"
};
static const ::_pbi::DescriptorTable* PROTOBUF_NONNULL const
    descriptor_table_io_2funmango_2fv1alpha1_2fparser_2eproto_deps[1] = {
        &::descriptor_table_io_2funmango_2fv1alpha1_2fast_2eproto,
};
static ::absl::once_flag descriptor_table_io_2funmango_2fv1alpha1_2fparser_2eproto_once;
PROTOBUF_CONSTINIT const ::_pbi::DescriptorTable descriptor_table_io_2funmango_2fv1alpha1_2fparser_2eproto = {
    false,
    false,
    516,
    descriptor_table_protodef_io_2funmango_2fv1alpha1_2fparser_2eproto,
    "io/unmango/v1alpha1/parser.proto",
    &descriptor_table_io_2funmango_2fv1alpha1_2fparser_2eproto_once,
    descriptor_table_io_2funmango_2fv1alpha1_2fparser_2eproto_deps,
    1,
    2,
    schemas,
    file_default_instances,
    TableStruct_io_2funmango_2fv1alpha1_2fparser_2eproto::offsets,
    file_level_enum_descriptors_io_2funmango_2fv1alpha1_2fparser_2eproto,
    file_level_service_descriptors_io_2funmango_2fv1alpha1_2fparser_2eproto,
};
namespace io {
namespace unmango {
namespace v1alpha1 {
// ===================================================================

class ParseRequest::_Internal {
 public:
  using HasBits =
      decltype(std::declval<ParseRequest>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(ParseRequest, _impl_._has_bits_);
};

ParseRequest::ParseRequest(::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, ParseRequest_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:io.unmango.v1alpha1.ParseRequest)
}
PROTOBUF_NDEBUG_INLINE ParseRequest::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
    const ::io::unmango::v1alpha1::ParseRequest& from_msg)
      : _has_bits_{from._has_bits_},
        _cached_size_{0},
        text_(arena, from.text_) {}

ParseRequest::ParseRequest(
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena,
    const ParseRequest& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, ParseRequest_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  ParseRequest* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);

  // @@protoc_insertion_point(copy_constructor:io.unmango.v1alpha1.ParseRequest)
}
PROTOBUF_NDEBUG_INLINE ParseRequest::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
      : _cached_size_{0},
        text_(arena) {}

inline void ParseRequest::SharedCtor(::_pb::Arena* PROTOBUF_NULLABLE arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
}
ParseRequest::~ParseRequest() {
  // @@protoc_insertion_point(destructor:io.unmango.v1alpha1.ParseRequest)
  SharedDtor(*this);
}
inline void ParseRequest::SharedDtor(MessageLite& self) {
  ParseRequest& this_ = static_cast<ParseRequest&>(self);
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.text_.Destroy();
  this_._impl_.~Impl_();
}

inline void* PROTOBUF_NONNULL ParseRequest::PlacementNew_(
    const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena) {
  return ::new (mem) ParseRequest(arena);
}
constexpr auto ParseRequest::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::CopyInit(sizeof(ParseRequest),
                                            alignof(ParseRequest));
}
constexpr auto ParseRequest::InternalGenerateClassData_() {
  return ::google::protobuf::internal::ClassDataFull{
      ::google::protobuf::internal::ClassData{
          &_ParseRequest_default_instance_._instance,
          &_table_.header,
          nullptr,  // OnDemandRegisterArenaDtor
          nullptr,  // IsInitialized
          &ParseRequest::MergeImpl,
          ::google::protobuf::Message::GetNewImpl<ParseRequest>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &ParseRequest::SharedDtor,
          ::google::protobuf::Message::GetClearImpl<ParseRequest>(), &ParseRequest::ByteSizeLong,
              &ParseRequest::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(ParseRequest, _impl_._cached_size_),
          false,
      },
      &ParseRequest::kDescriptorMethods,
      &descriptor_table_io_2funmango_2fv1alpha1_2fparser_2eproto,
      nullptr,  // tracker
  };
}

PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const ::google::protobuf::internal::ClassDataFull
        ParseRequest_class_data_ =
            ParseRequest::InternalGenerateClassData_();

const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL ParseRequest::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&ParseRequest_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(ParseRequest_class_data_.tc_table);
  return ParseRequest_class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<0, 1, 0, 45, 2>
ParseRequest::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(ParseRequest, _impl_._has_bits_),
    0, // no _extensions_
    1, 0,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967294,  // skipmap
    offsetof(decltype(_table_), field_entries),
    1,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    ParseRequest_class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::io::unmango::v1alpha1::ParseRequest>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // string text = 1 [json_name = "text"];
    {::_pbi::TcParser::FastUS1,
     {10, 0, 0, PROTOBUF_FIELD_OFFSET(ParseRequest, _impl_.text_)}},
  }}, {{
    65535, 65535
  }}, {{
    // string text = 1 [json_name = "text"];
    {PROTOBUF_FIELD_OFFSET(ParseRequest, _impl_.text_), _Internal::kHasBitsOffset + 0, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kUtf8String | ::_fl::kRepAString)},
  }},
  // no aux_entries
  {{
    "\40\4\0\0\0\0\0\0"
    "io.unmango.v1alpha1.ParseRequest"
    "text"
  }},
};
PROTOBUF_NOINLINE void ParseRequest::Clear() {
// @@protoc_insertion_point(message_clear_start:io.unmango.v1alpha1.ParseRequest)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if ((cached_has_bits & 0x00000001u) != 0) {
    _impl_.text_.ClearNonDefaultToEmpty();
  }
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::uint8_t* PROTOBUF_NONNULL ParseRequest::_InternalSerialize(
    const ::google::protobuf::MessageLite& base, ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) {
  const ParseRequest& this_ = static_cast<const ParseRequest&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::uint8_t* PROTOBUF_NONNULL ParseRequest::_InternalSerialize(
    ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
  const ParseRequest& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(serialize_to_array_start:io.unmango.v1alpha1.ParseRequest)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  // string text = 1 [json_name = "text"];
  if ((this_._impl_._has_bits_[0] & 0x00000001u) != 0) {
    if (!this_._internal_text().empty()) {
      const std::string& _s = this_._internal_text();
      ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
          _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "io.unmango.v1alpha1.ParseRequest.text");
      target = stream->WriteStringMaybeAliased(1, _s, target);
    }
  }

  if (ABSL_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:io.unmango.v1alpha1.ParseRequest)
  return target;
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::size_t ParseRequest::ByteSizeLong(const MessageLite& base) {
  const ParseRequest& this_ = static_cast<const ParseRequest&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::size_t ParseRequest::ByteSizeLong() const {
  const ParseRequest& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(message_byte_size_start:io.unmango.v1alpha1.ParseRequest)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void)cached_has_bits;

   {
    // string text = 1 [json_name = "text"];
    cached_has_bits = this_._impl_._has_bits_[0];
    if ((cached_has_bits & 0x00000001u) != 0) {
      if (!this_._internal_text().empty()) {
        total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                        this_._internal_text());
      }
    }
  }
  return this_.MaybeComputeUnknownFieldsSize(total_size,
                                             &this_._impl_._cached_size_);
}

void ParseRequest::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<ParseRequest*>(&to_msg);
  auto& from = static_cast<const ParseRequest&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:io.unmango.v1alpha1.ParseRequest)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if ((cached_has_bits & 0x00000001u) != 0) {
    if (!from._internal_text().empty()) {
      _this->_internal_set_text(from._internal_text());
    } else {
      if (_this->_impl_.text_.IsDefault()) {
        _this->_internal_set_text("");
      }
    }
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void ParseRequest::CopyFrom(const ParseRequest& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:io.unmango.v1alpha1.ParseRequest)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void ParseRequest::InternalSwap(ParseRequest* PROTOBUF_RESTRICT PROTOBUF_NONNULL other) {
  using std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.text_, &other->_impl_.text_, arena);
}

::google::protobuf::Metadata ParseRequest::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class ParseResponse::_Internal {
 public:
  using HasBits =
      decltype(std::declval<ParseResponse>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(ParseResponse, _impl_._has_bits_);
};

void ParseResponse::clear_file() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (_impl_.file_ != nullptr) _impl_.file_->Clear();
  _impl_._has_bits_[0] &= ~0x00000001u;
}
ParseResponse::ParseResponse(::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, ParseResponse_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:io.unmango.v1alpha1.ParseResponse)
}
PROTOBUF_NDEBUG_INLINE ParseResponse::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
    const ::io::unmango::v1alpha1::ParseResponse& from_msg)
      : _has_bits_{from._has_bits_},
        _cached_size_{0} {}

ParseResponse::ParseResponse(
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena,
    const ParseResponse& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, ParseResponse_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  ParseResponse* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  ::uint32_t cached_has_bits = _impl_._has_bits_[0];
  _impl_.file_ = ((cached_has_bits & 0x00000001u) != 0)
                ? ::google::protobuf::Message::CopyConstruct(arena, *from._impl_.file_)
                : nullptr;

  // @@protoc_insertion_point(copy_constructor:io.unmango.v1alpha1.ParseResponse)
}
PROTOBUF_NDEBUG_INLINE ParseResponse::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
      : _cached_size_{0} {}

inline void ParseResponse::SharedCtor(::_pb::Arena* PROTOBUF_NULLABLE arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  _impl_.file_ = {};
}
ParseResponse::~ParseResponse() {
  // @@protoc_insertion_point(destructor:io.unmango.v1alpha1.ParseResponse)
  SharedDtor(*this);
}
inline void ParseResponse::SharedDtor(MessageLite& self) {
  ParseResponse& this_ = static_cast<ParseResponse&>(self);
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  delete this_._impl_.file_;
  this_._impl_.~Impl_();
}

inline void* PROTOBUF_NONNULL ParseResponse::PlacementNew_(
    const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena) {
  return ::new (mem) ParseResponse(arena);
}
constexpr auto ParseResponse::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::ZeroInit(sizeof(ParseResponse),
                                            alignof(ParseResponse));
}
constexpr auto ParseResponse::InternalGenerateClassData_() {
  return ::google::protobuf::internal::ClassDataFull{
      ::google::protobuf::internal::ClassData{
          &_ParseResponse_default_instance_._instance,
          &_table_.header,
          nullptr,  // OnDemandRegisterArenaDtor
          nullptr,  // IsInitialized
          &ParseResponse::MergeImpl,
          ::google::protobuf::Message::GetNewImpl<ParseResponse>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &ParseResponse::SharedDtor,
          ::google::protobuf::Message::GetClearImpl<ParseResponse>(), &ParseResponse::ByteSizeLong,
              &ParseResponse::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(ParseResponse, _impl_._cached_size_),
          false,
      },
      &ParseResponse::kDescriptorMethods,
      &descriptor_table_io_2funmango_2fv1alpha1_2fparser_2eproto,
      nullptr,  // tracker
  };
}

PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const ::google::protobuf::internal::ClassDataFull
        ParseResponse_class_data_ =
            ParseResponse::InternalGenerateClassData_();

const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL ParseResponse::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&ParseResponse_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(ParseResponse_class_data_.tc_table);
  return ParseResponse_class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<0, 1, 1, 0, 2>
ParseResponse::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(ParseResponse, _impl_._has_bits_),
    0, // no _extensions_
    1, 0,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967294,  // skipmap
    offsetof(decltype(_table_), field_entries),
    1,  // num_field_entries
    1,  // num_aux_entries
    offsetof(decltype(_table_), aux_entries),
    ParseResponse_class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::io::unmango::v1alpha1::ParseResponse>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // .io.unmango.v1alpha1.File file = 1 [json_name = "file"];
    {::_pbi::TcParser::FastMtS1,
     {10, 0, 0, PROTOBUF_FIELD_OFFSET(ParseResponse, _impl_.file_)}},
  }}, {{
    65535, 65535
  }}, {{
    // .io.unmango.v1alpha1.File file = 1 [json_name = "file"];
    {PROTOBUF_FIELD_OFFSET(ParseResponse, _impl_.file_), _Internal::kHasBitsOffset + 0, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kMessage | ::_fl::kTvTable)},
  }},
  {{
      {::_pbi::TcParser::GetTable<::io::unmango::v1alpha1::File>()},
  }},
  {{
  }},
};
PROTOBUF_NOINLINE void ParseResponse::Clear() {
// @@protoc_insertion_point(message_clear_start:io.unmango.v1alpha1.ParseResponse)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if ((cached_has_bits & 0x00000001u) != 0) {
    ABSL_DCHECK(_impl_.file_ != nullptr);
    _impl_.file_->Clear();
  }
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::uint8_t* PROTOBUF_NONNULL ParseResponse::_InternalSerialize(
    const ::google::protobuf::MessageLite& base, ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) {
  const ParseResponse& this_ = static_cast<const ParseResponse&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::uint8_t* PROTOBUF_NONNULL ParseResponse::_InternalSerialize(
    ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
  const ParseResponse& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(serialize_to_array_start:io.unmango.v1alpha1.ParseResponse)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = this_._impl_._has_bits_[0];
  // .io.unmango.v1alpha1.File file = 1 [json_name = "file"];
  if ((cached_has_bits & 0x00000001u) != 0) {
    target = ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
        1, *this_._impl_.file_, this_._impl_.file_->GetCachedSize(), target,
        stream);
  }

  if (ABSL_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:io.unmango.v1alpha1.ParseResponse)
  return target;
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::size_t ParseResponse::ByteSizeLong(const MessageLite& base) {
  const ParseResponse& this_ = static_cast<const ParseResponse&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::size_t ParseResponse::ByteSizeLong() const {
  const ParseResponse& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(message_byte_size_start:io.unmango.v1alpha1.ParseResponse)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void)cached_has_bits;

   {
    // .io.unmango.v1alpha1.File file = 1 [json_name = "file"];
    cached_has_bits = this_._impl_._has_bits_[0];
    if ((cached_has_bits & 0x00000001u) != 0) {
      total_size += 1 +
                    ::google::protobuf::internal::WireFormatLite::MessageSize(*this_._impl_.file_);
    }
  }
  return this_.MaybeComputeUnknownFieldsSize(total_size,
                                             &this_._impl_._cached_size_);
}

void ParseResponse::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<ParseResponse*>(&to_msg);
  auto& from = static_cast<const ParseResponse&>(from_msg);
  ::google::protobuf::Arena* arena = _this->GetArena();
  // @@protoc_insertion_point(class_specific_merge_from_start:io.unmango.v1alpha1.ParseResponse)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if ((cached_has_bits & 0x00000001u) != 0) {
    ABSL_DCHECK(from._impl_.file_ != nullptr);
    if (_this->_impl_.file_ == nullptr) {
      _this->_impl_.file_ = ::google::protobuf::Message::CopyConstruct(arena, *from._impl_.file_);
    } else {
      _this->_impl_.file_->MergeFrom(*from._impl_.file_);
    }
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void ParseResponse::CopyFrom(const ParseResponse& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:io.unmango.v1alpha1.ParseResponse)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void ParseResponse::InternalSwap(ParseResponse* PROTOBUF_RESTRICT PROTOBUF_NONNULL other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  swap(_impl_.file_, other->_impl_.file_);
}

::google::protobuf::Metadata ParseResponse::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// @@protoc_insertion_point(namespace_scope)
}  // namespace v1alpha1
}  // namespace unmango
}  // namespace io
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::std::false_type
    _static_init2_ [[maybe_unused]] =
        (::_pbi::AddDescriptors(&descriptor_table_io_2funmango_2fv1alpha1_2fparser_2eproto),
         ::std::false_type{});
#include "google/protobuf/port_undef.inc"
