// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: io/unmango/v1alpha1/parser.proto
// Protobuf C++ Version: 6.30.0

#ifndef io_2funmango_2fv1alpha1_2fparser_2eproto_2epb_2eh
#define io_2funmango_2fv1alpha1_2fparser_2eproto_2epb_2eh

#include <limits>
#include <string>
#include <type_traits>
#include <utility>

#include "google/protobuf/runtime_version.h"
#if PROTOBUF_VERSION != 6030000
#error "Protobuf C++ gencode is built with an incompatible version of"
#error "Protobuf C++ headers/runtime. See"
#error "https://protobuf.dev/support/cross-version-runtime-guarantee/#cpp"
#endif
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/arena.h"
#include "google/protobuf/arenastring.h"
#include "google/protobuf/generated_message_tctable_decl.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/metadata_lite.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/message.h"
#include "google/protobuf/message_lite.h"
#include "google/protobuf/repeated_field.h"  // IWYU pragma: export
#include "google/protobuf/extension_set.h"  // IWYU pragma: export
#include "google/protobuf/unknown_field_set.h"
#include "io/unmango/v1alpha1/ast.pb.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"

#define PROTOBUF_INTERNAL_EXPORT_io_2funmango_2fv1alpha1_2fparser_2eproto

namespace google {
namespace protobuf {
namespace internal {
template <typename T>
::absl::string_view GetAnyMessageName();
}  // namespace internal
}  // namespace protobuf
}  // namespace google

// Internal implementation detail -- do not use these members.
struct TableStruct_io_2funmango_2fv1alpha1_2fparser_2eproto {
  static const ::uint32_t offsets[];
};
extern "C" {
extern const ::google::protobuf::internal::DescriptorTable descriptor_table_io_2funmango_2fv1alpha1_2fparser_2eproto;
}  // extern "C"
namespace io {
namespace unmango {
namespace v1alpha1 {
class ParseRequest;
struct ParseRequestDefaultTypeInternal;
extern ParseRequestDefaultTypeInternal _ParseRequest_default_instance_;
extern const ::google::protobuf::internal::ClassDataFull ParseRequest_class_data_;
class ParseResponse;
struct ParseResponseDefaultTypeInternal;
extern ParseResponseDefaultTypeInternal _ParseResponse_default_instance_;
extern const ::google::protobuf::internal::ClassDataFull ParseResponse_class_data_;
}  // namespace v1alpha1
}  // namespace unmango
}  // namespace io
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google

namespace io {
namespace unmango {
namespace v1alpha1 {

// ===================================================================


// -------------------------------------------------------------------

class ParseRequest final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:io.unmango.v1alpha1.ParseRequest) */ {
 public:
  inline ParseRequest() : ParseRequest(nullptr) {}
  ~ParseRequest() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(ParseRequest* PROTOBUF_NONNULL msg, std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(ParseRequest));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR ParseRequest(::google::protobuf::internal::ConstantInitialized);

  inline ParseRequest(const ParseRequest& from) : ParseRequest(nullptr, from) {}
  inline ParseRequest(ParseRequest&& from) noexcept
      : ParseRequest(nullptr, std::move(from)) {}
  inline ParseRequest& operator=(const ParseRequest& from) {
    CopyFrom(from);
    return *this;
  }
  inline ParseRequest& operator=(ParseRequest&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const ParseRequest& default_instance() {
    return *reinterpret_cast<const ParseRequest*>(
        &_ParseRequest_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 0;
  friend void swap(ParseRequest& a, ParseRequest& b) { a.Swap(&b); }
  inline void Swap(ParseRequest* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(ParseRequest* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  ParseRequest* PROTOBUF_NONNULL New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<ParseRequest>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const ParseRequest& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const ParseRequest& from) { ParseRequest::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(ParseRequest* PROTOBUF_NONNULL other);
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "io.unmango.v1alpha1.ParseRequest"; }

 protected:
  explicit ParseRequest(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  ParseRequest(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const ParseRequest& from);
  ParseRequest(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, ParseRequest&& from) noexcept
      : ParseRequest(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_();

  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kTextFieldNumber = 1,
  };
  // string text = 1 [json_name = "text"];
  void clear_text() ;
  const std::string& text() const;
  template <typename Arg_ = const std::string&, typename... Args_>
  void set_text(Arg_&& arg, Args_... args);
  std::string* PROTOBUF_NONNULL mutable_text();
  [[nodiscard]] std::string* PROTOBUF_NULLABLE release_text();
  void set_allocated_text(std::string* PROTOBUF_NULLABLE value);

  private:
  const std::string& _internal_text() const;
  PROTOBUF_ALWAYS_INLINE void _internal_set_text(const std::string& value);
  std::string* PROTOBUF_NONNULL _internal_mutable_text();

  public:
  // @@protoc_insertion_point(class_scope:io.unmango.v1alpha1.ParseRequest)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<0, 1,
                                   0, 45,
                                   2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const ParseRequest& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::google::protobuf::internal::ArenaStringPtr text_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_io_2funmango_2fv1alpha1_2fparser_2eproto;
};

extern const ::google::protobuf::internal::ClassDataFull ParseRequest_class_data_;
// -------------------------------------------------------------------

class ParseResponse final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:io.unmango.v1alpha1.ParseResponse) */ {
 public:
  inline ParseResponse() : ParseResponse(nullptr) {}
  ~ParseResponse() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(ParseResponse* PROTOBUF_NONNULL msg, std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(ParseResponse));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR ParseResponse(::google::protobuf::internal::ConstantInitialized);

  inline ParseResponse(const ParseResponse& from) : ParseResponse(nullptr, from) {}
  inline ParseResponse(ParseResponse&& from) noexcept
      : ParseResponse(nullptr, std::move(from)) {}
  inline ParseResponse& operator=(const ParseResponse& from) {
    CopyFrom(from);
    return *this;
  }
  inline ParseResponse& operator=(ParseResponse&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const ParseResponse& default_instance() {
    return *reinterpret_cast<const ParseResponse*>(
        &_ParseResponse_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 1;
  friend void swap(ParseResponse& a, ParseResponse& b) { a.Swap(&b); }
  inline void Swap(ParseResponse* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(ParseResponse* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  ParseResponse* PROTOBUF_NONNULL New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<ParseResponse>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const ParseResponse& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const ParseResponse& from) { ParseResponse::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(ParseResponse* PROTOBUF_NONNULL other);
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "io.unmango.v1alpha1.ParseResponse"; }

 protected:
  explicit ParseResponse(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  ParseResponse(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const ParseResponse& from);
  ParseResponse(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, ParseResponse&& from) noexcept
      : ParseResponse(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_();

  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kFileFieldNumber = 1,
  };
  // .io.unmango.v1alpha1.File file = 1 [json_name = "file"];
  bool has_file() const;
  void clear_file() ;
  const ::io::unmango::v1alpha1::File& file() const;
  [[nodiscard]] ::io::unmango::v1alpha1::File* PROTOBUF_NULLABLE release_file();
  ::io::unmango::v1alpha1::File* PROTOBUF_NONNULL mutable_file();
  void set_allocated_file(::io::unmango::v1alpha1::File* PROTOBUF_NULLABLE value);
  void unsafe_arena_set_allocated_file(::io::unmango::v1alpha1::File* PROTOBUF_NULLABLE value);
  ::io::unmango::v1alpha1::File* PROTOBUF_NULLABLE unsafe_arena_release_file();

  private:
  const ::io::unmango::v1alpha1::File& _internal_file() const;
  ::io::unmango::v1alpha1::File* PROTOBUF_NONNULL _internal_mutable_file();

  public:
  // @@protoc_insertion_point(class_scope:io.unmango.v1alpha1.ParseResponse)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<0, 1,
                                   1, 0,
                                   2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const ParseResponse& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::io::unmango::v1alpha1::File* PROTOBUF_NULLABLE file_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_io_2funmango_2fv1alpha1_2fparser_2eproto;
};

extern const ::google::protobuf::internal::ClassDataFull ParseResponse_class_data_;

// ===================================================================




// ===================================================================


#ifdef __GNUC__
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// -------------------------------------------------------------------

// ParseRequest

// string text = 1 [json_name = "text"];
inline void ParseRequest::clear_text() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.text_.ClearToEmpty();
  _impl_._has_bits_[0] &= ~0x00000001u;
}
inline const std::string& ParseRequest::text() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:io.unmango.v1alpha1.ParseRequest.text)
  return _internal_text();
}
template <typename Arg_, typename... Args_>
PROTOBUF_ALWAYS_INLINE void ParseRequest::set_text(Arg_&& arg, Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000001u;
  _impl_.text_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:io.unmango.v1alpha1.ParseRequest.text)
}
inline std::string* PROTOBUF_NONNULL ParseRequest::mutable_text()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  std::string* _s = _internal_mutable_text();
  // @@protoc_insertion_point(field_mutable:io.unmango.v1alpha1.ParseRequest.text)
  return _s;
}
inline const std::string& ParseRequest::_internal_text() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.text_.Get();
}
inline void ParseRequest::_internal_set_text(const std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000001u;
  _impl_.text_.Set(value, GetArena());
}
inline std::string* PROTOBUF_NONNULL ParseRequest::_internal_mutable_text() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000001u;
  return _impl_.text_.Mutable( GetArena());
}
inline std::string* PROTOBUF_NULLABLE ParseRequest::release_text() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:io.unmango.v1alpha1.ParseRequest.text)
  if ((_impl_._has_bits_[0] & 0x00000001u) == 0) {
    return nullptr;
  }
  _impl_._has_bits_[0] &= ~0x00000001u;
  auto* released = _impl_.text_.Release();
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString()) {
    _impl_.text_.Set("", GetArena());
  }
  return released;
}
inline void ParseRequest::set_allocated_text(std::string* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    _impl_._has_bits_[0] |= 0x00000001u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000001u;
  }
  _impl_.text_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.text_.IsDefault()) {
    _impl_.text_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:io.unmango.v1alpha1.ParseRequest.text)
}

// -------------------------------------------------------------------

// ParseResponse

// .io.unmango.v1alpha1.File file = 1 [json_name = "file"];
inline bool ParseResponse::has_file() const {
  bool value = (_impl_._has_bits_[0] & 0x00000001u) != 0;
  PROTOBUF_ASSUME(!value || _impl_.file_ != nullptr);
  return value;
}
inline const ::io::unmango::v1alpha1::File& ParseResponse::_internal_file() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  const ::io::unmango::v1alpha1::File* p = _impl_.file_;
  return p != nullptr ? *p : reinterpret_cast<const ::io::unmango::v1alpha1::File&>(::io::unmango::v1alpha1::_File_default_instance_);
}
inline const ::io::unmango::v1alpha1::File& ParseResponse::file() const ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:io.unmango.v1alpha1.ParseResponse.file)
  return _internal_file();
}
inline void ParseResponse::unsafe_arena_set_allocated_file(
    ::io::unmango::v1alpha1::File* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (GetArena() == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.file_);
  }
  _impl_.file_ = reinterpret_cast<::io::unmango::v1alpha1::File*>(value);
  if (value != nullptr) {
    _impl_._has_bits_[0] |= 0x00000001u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000001u;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:io.unmango.v1alpha1.ParseResponse.file)
}
inline ::io::unmango::v1alpha1::File* PROTOBUF_NULLABLE ParseResponse::release_file() {
  ::google::protobuf::internal::TSanWrite(&_impl_);

  _impl_._has_bits_[0] &= ~0x00000001u;
  ::io::unmango::v1alpha1::File* released = _impl_.file_;
  _impl_.file_ = nullptr;
  if (::google::protobuf::internal::DebugHardenForceCopyInRelease()) {
    auto* old = reinterpret_cast<::google::protobuf::MessageLite*>(released);
    released = ::google::protobuf::internal::DuplicateIfNonNull(released);
    if (GetArena() == nullptr) {
      delete old;
    }
  } else {
    if (GetArena() != nullptr) {
      released = ::google::protobuf::internal::DuplicateIfNonNull(released);
    }
  }
  return released;
}
inline ::io::unmango::v1alpha1::File* PROTOBUF_NULLABLE ParseResponse::unsafe_arena_release_file() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:io.unmango.v1alpha1.ParseResponse.file)

  _impl_._has_bits_[0] &= ~0x00000001u;
  ::io::unmango::v1alpha1::File* temp = _impl_.file_;
  _impl_.file_ = nullptr;
  return temp;
}
inline ::io::unmango::v1alpha1::File* PROTOBUF_NONNULL ParseResponse::_internal_mutable_file() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (_impl_.file_ == nullptr) {
    auto* p = ::google::protobuf::Message::DefaultConstruct<::io::unmango::v1alpha1::File>(GetArena());
    _impl_.file_ = reinterpret_cast<::io::unmango::v1alpha1::File*>(p);
  }
  return _impl_.file_;
}
inline ::io::unmango::v1alpha1::File* PROTOBUF_NONNULL ParseResponse::mutable_file()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  _impl_._has_bits_[0] |= 0x00000001u;
  ::io::unmango::v1alpha1::File* _msg = _internal_mutable_file();
  // @@protoc_insertion_point(field_mutable:io.unmango.v1alpha1.ParseResponse.file)
  return _msg;
}
inline void ParseResponse::set_allocated_file(::io::unmango::v1alpha1::File* PROTOBUF_NULLABLE value) {
  ::google::protobuf::Arena* message_arena = GetArena();
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (message_arena == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.file_);
  }

  if (value != nullptr) {
    ::google::protobuf::Arena* submessage_arena = reinterpret_cast<::google::protobuf::Message*>(value)->GetArena();
    if (message_arena != submessage_arena) {
      value = ::google::protobuf::internal::GetOwnedMessage(message_arena, value, submessage_arena);
    }
    _impl_._has_bits_[0] |= 0x00000001u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000001u;
  }

  _impl_.file_ = reinterpret_cast<::io::unmango::v1alpha1::File*>(value);
  // @@protoc_insertion_point(field_set_allocated:io.unmango.v1alpha1.ParseResponse.file)
}

#ifdef __GNUC__
#pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)
}  // namespace v1alpha1
}  // namespace unmango
}  // namespace io


// @@protoc_insertion_point(global_scope)

#include "google/protobuf/port_undef.inc"

#endif  // io_2funmango_2fv1alpha1_2fparser_2eproto_2epb_2eh
