// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: io/unmango/v1alpha1/parser.proto

#include "io/unmango/v1alpha1/parser.pb.h"
#include "io/unmango/v1alpha1/parser.grpc.pb.h"

#include <functional>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/impl/channel_interface.h>
#include <grpcpp/impl/client_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/rpc_service_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/sync_stream.h>
namespace io {
namespace unmango {
namespace v1alpha1 {

static const char* ParserService_method_names[] = {
  "/io.unmango.v1alpha1.ParserService/Parse",
};

std::unique_ptr< ParserService::Stub> ParserService::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< ParserService::Stub> stub(new ParserService::Stub(channel, options));
  return stub;
}

ParserService::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options)
  : channel_(channel), rpcmethod_Parse_(ParserService_method_names[0], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status ParserService::Stub::Parse(::grpc::ClientContext* context, const ::io::unmango::v1alpha1::ParseRequest& request, ::io::unmango::v1alpha1::ParseResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::io::unmango::v1alpha1::ParseRequest, ::io::unmango::v1alpha1::ParseResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_Parse_, context, request, response);
}

void ParserService::Stub::async::Parse(::grpc::ClientContext* context, const ::io::unmango::v1alpha1::ParseRequest* request, ::io::unmango::v1alpha1::ParseResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::io::unmango::v1alpha1::ParseRequest, ::io::unmango::v1alpha1::ParseResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_Parse_, context, request, response, std::move(f));
}

void ParserService::Stub::async::Parse(::grpc::ClientContext* context, const ::io::unmango::v1alpha1::ParseRequest* request, ::io::unmango::v1alpha1::ParseResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_Parse_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::io::unmango::v1alpha1::ParseResponse>* ParserService::Stub::PrepareAsyncParseRaw(::grpc::ClientContext* context, const ::io::unmango::v1alpha1::ParseRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::io::unmango::v1alpha1::ParseResponse, ::io::unmango::v1alpha1::ParseRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_Parse_, context, request);
}

::grpc::ClientAsyncResponseReader< ::io::unmango::v1alpha1::ParseResponse>* ParserService::Stub::AsyncParseRaw(::grpc::ClientContext* context, const ::io::unmango::v1alpha1::ParseRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncParseRaw(context, request, cq);
  result->StartCall();
  return result;
}

ParserService::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      ParserService_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< ParserService::Service, ::io::unmango::v1alpha1::ParseRequest, ::io::unmango::v1alpha1::ParseResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](ParserService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::io::unmango::v1alpha1::ParseRequest* req,
             ::io::unmango::v1alpha1::ParseResponse* resp) {
               return service->Parse(ctx, req, resp);
             }, this)));
}

ParserService::Service::~Service() {
}

::grpc::Status ParserService::Service::Parse(::grpc::ServerContext* context, const ::io::unmango::v1alpha1::ParseRequest* request, ::io::unmango::v1alpha1::ParseResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace io
}  // namespace unmango
}  // namespace v1alpha1

