name: CI

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

jobs:
  build:
    name: Build and Test
    runs-on: lang-runners
    container: ghcr.io/catthehacker/ubuntu:runner-latest
    env:
      VCPKG_BINARY_SOURCES: "clear;x-gha,readwrite"
    steps:
      - uses: actions/checkout@v4

      - run: make .make bin

      - uses: actions/cache@v4
        with:
          path: ${{github.workspace}}/build
          key: ${{ runner.os }}-${{ hashFiles('CMakeLists.txt') }}
          restore-keys: |
            ${{ runner.os }}-

      - uses: actions/setup-dotnet@v4
        with:
          global-json-file: global.json
        env:
          DOTNET_INSTALL_DIR: ${{ github.workspace }}/bin

      - uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
          cache-dependency-path: go.sum

      - name: Export GitHub Actions cache environment variables
        uses: actions/github-script@v7
        with:
          script: |
            core.exportVariable('ACTIONS_CACHE_URL', process.env.ACTIONS_CACHE_URL || '');
            core.exportVariable('ACTIONS_RUNTIME_TOKEN', process.env.ACTIONS_RUNTIME_TOKEN || '');

      - uses: KyleMayes/install-llvm-action@v2
        with:
          version: '19.1'
          force-url: https://github.com/llvm/llvm-project/releases/download/llvmorg-19.1.7/LLVM-19.1.7-Linux-X64.tar.xz

      - run: sudo ln -s ${{ env.LLVM_PATH }}/lib/

      - run: make bin/vcpkg

      - run: bin/vcpkg install
        if: false

      - run: make ci
